/*
       Implementation of Payroll Management System
 */

package payroll;
 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author Md. Ariful Islam Joy
 */
public class PayRollHome extends javax.swing.JFrame {

    /**
     * Creates new form PayRollForm
     */
    public PayRollHome() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdId = new javax.swing.JTextField();
        EmpId = new javax.swing.JTextField();
        AdPass = new javax.swing.JPasswordField();
        EmpPass = new javax.swing.JPasswordField();
        AdLog = new javax.swing.JButton();
        EmpLog = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 102));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome   to   PRoll's");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Easyer way toward Payroll Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Admin Panel  ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Employee Panel ");

        AdId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdId.setText("Admin ID");
        AdId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdIdFocusLost(evt);
            }
        });

        EmpId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpId.setText(" Employee ID");
        EmpId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmpIdFocusLost(evt);
            }
        });

        AdPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdPass.setText(" Password");
        AdPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdPassFocusLost(evt);
            }
        });

        EmpPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpPass.setText(" Password");
        EmpPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmpPassFocusLost(evt);
            }
        });

        AdLog.setBackground(new java.awt.Color(51, 51, 51));
        AdLog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdLog.setForeground(new java.awt.Color(0, 204, 204));
        AdLog.setText("Login");
        AdLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdLogMouseClicked(evt);
            }
        });

        EmpLog.setBackground(new java.awt.Color(51, 51, 51));
        EmpLog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpLog.setForeground(new java.awt.Color(0, 204, 204));
        EmpLog.setText("Login");
        EmpLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpLogMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Developed by Md. Ariful Islam Joy (CSE-18,RUET)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(219, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AdPass, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(AdLog)
                                .addComponent(AdId, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(EmpId, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(EmpPass)
                        .addComponent(EmpLog, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdLog)
                    .addComponent(EmpLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdIdFocusGained
        // TODO add your handling code here:
        AdId.selectAll();
    }//GEN-LAST:event_AdIdFocusGained

    private void AdIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdIdFocusLost
        // TODO add your handling code here:
        if(AdId.getText().isEmpty())
            AdId.setText("Admin ID");
    }//GEN-LAST:event_AdIdFocusLost

    private void EmpIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpIdFocusGained
        // TODO add your handling code here:
        EmpId.selectAll();
    }//GEN-LAST:event_EmpIdFocusGained

    private void EmpIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpIdFocusLost
        // TODO add your handling code here:
        if (EmpId.getText().isEmpty())
            EmpId.setText("Employee ID");
    }//GEN-LAST:event_EmpIdFocusLost

    private void AdPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdPassFocusGained
        // TODO add your handling code here:
        AdPass.selectAll();
    }//GEN-LAST:event_AdPassFocusGained

    private void AdPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdPassFocusLost
        // TODO add your handling code here:
        if (AdPass.getText().isEmpty())
            AdPass.setText("Password");
    }//GEN-LAST:event_AdPassFocusLost

    private void EmpPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpPassFocusGained
        // TODO add your handling code here:
        EmpPass.selectAll();
    }//GEN-LAST:event_EmpPassFocusGained

    private void EmpPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpPassFocusLost
        // TODO add your handling code here:
        if (EmpPass.getText().isEmpty())
            EmpPass.setText("Password");
    }//GEN-LAST:event_EmpPassFocusLost

    private void AdLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdLogMouseClicked
        // Handling with database
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pay-roll management?zeroDateTimeBehavior=convertToNull","root","");
                Statement stmt = con.createStatement();
                String sql;
                sql = "select *from admin where ID= '"+AdId.getText()+"'and Password = '"+AdPass.getText()+"'";
                
                ResultSet rs = stmt.executeQuery(sql);
                
                if(rs.next()&&(rs.getString("ID").equals(AdId.getText()))&&(rs.getString("Password").equals(AdPass.getText()))){
                    new AdminPage().setVisible(true);
                    this.setVisible(false);
                }
                else{
                    jLabel4.setText("Invalid ID or Password . . .");
                }
                con.close();
            }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
         
         // Handling with File
         /*  String Id;
        String Password;
      
        try
        {
            try (BufferedReader rdr = new BufferedReader(new FileReader("Admin.txt"))) {
                Id=rdr.readLine();
                Password=rdr.readLine();
            }
            if(Id.equals(AdId.getText())&&Password.equals(AdPass.getText())){
                new AdminPage().setVisible(true);
                this.setVisible(false);
            }
            else{
                jLabel4.setText("Invalid ID or Password...");
            }
        }
        catch(Exception e){
        }
        */
      
    }//GEN-LAST:event_AdLogMouseClicked

    private void EmpLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpLogMouseClicked
        //   Employee Log in
       //    Handling with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pay-roll management?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
            String sql;
            sql="select *from employee where ID='"+EmpId.getText()+"'and Password='"+EmpPass.getText()+"'";
            
            ResultSet rs=stmt.executeQuery(sql);
            
            if(rs.next()&&(rs.getString("ID").equals(EmpId.getText()))&&(rs.getString("Password").equals(EmpPass.getText()))){
                new EmployeePage().setVisible(true);
                this.setVisible(false);
            }
            else{
                jLabel7.setText("Invalid ID or Password . . .");
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_EmpLogMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
         jLabel7.setText(null);
         jLabel4.setText(null);
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayRollHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayRollHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayRollHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayRollHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(() ->{
            new PayRollHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdId;
    private javax.swing.JButton AdLog;
    private javax.swing.JPasswordField AdPass;
    private javax.swing.JTextField EmpId;
    private javax.swing.JButton EmpLog;
    private javax.swing.JPasswordField EmpPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
